#!/bin/bash
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;34m
[1] CrearUsuario \033[2;36m(Criar usuarios para SSH e OpenVPN)\033[1;33m
[2] RedefinirUsuario \033[2;36m(Opções para mudanças no usuario)\033[1;33m
[3] DetalleDeUsuario \033[2;36m(Mostra informações de um unico usuario !!)\033[1;33m
[4] DetalleDeUsuarios \033[2;36m(Mostra informações de todos os usuarios !!)\033[1;33m
[5] Speedtest \033[2;36m(Teste de conexão [velocidade de banda])\033[1;33m
[6] SystemDetalls \033[2;36m(Detalhes sobre o Sistema)\033[1;33m
[7] GraphicSystem \033[2;36m(Detalhes sobre o VpsPack)\033[1;33m
[8] Ayuda \033[2;36m(Mostrar um grafico com informações do sistema)\033[1;33m
[9] Block \033[2;36m(Bloquear um determinado IP)\033[1;33m
[10] Desblock \033[2;36m(Desbloquear um determinado IP)\033[1;33m
[11] Add-Host \033[2;36m(Adicionar um host)\033[1;33m
[12] Firewall-block \033[2;36m(Regras iptables block torrent, icmp [RISCOS])\033[1;33m
[13] ResetFirewall \033[2;36m(Retira todas as regras iptables [RISCOS])\033[1;33m
[14] BackupUsers \033[2;36m(Backup dos usuarios para reinstalação futura)\033[1;33m
[15] RestUsers \033[2;36m(Restaurar usuarios feito backup)\033[1;33m
[16] Banner \033[2;36m(Banner mensagem no ssh)\033[0m"
read -p "[1-24]: " opcao

case $opcao in
 1)  
  Usercreate
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 2)
  UserRedefine
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 3)
  detalhesuser
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 4)
  detalhesusers
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 5)
  speedtest
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 6)
  nbwmon
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 7)
  systemdetalhes
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 8)
  htop
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 9)
  Ayuda
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 10)
  block
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 11)
  desblock
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 12)
  add-host
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 13)
  firewall-block
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 14)
  resetFirewall
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 15)
  backupusers
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 16)
  restusers
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;; 
 17)
  banner
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;; 
  *)
  id > /dev/null 2> /dev/null
esac
