#!/bin/bash
echo -e "\033[1;32mEscoja las opciones:    \033[1;32mPara Salir Ctrl + C\033[1;33m
[1] CrearUsuario \033[2;36m(Crear usuarios para SSH y OpenVPN)\033[1;33m
[2] RedefinirUsuario \033[2;36m(Opcion para mudanzas de usuario)\033[1;33m
[3] DetalleDeUsuario \033[2;36m(Mostrar informacion de un unico usuario !!)\033[1;33m
[4] DetalleDeUsuarios \033[2;36m(Mostrar informacion de todos los usuarios !!)\033[1;33m
[5] Speedtest \033[2;36m(Tester de conexion [velocidad de banda])\033[1;33m
[6] SystemDetalls \033[2;36m(Detalles sobre el Sistema)\033[1;33m
[7] GraphicSystem \033[2;36m(Detalles sobre VpsPack)\033[1;33m
[8] Ayuda \033[2;36m(Mostrar un grafico com informacion del sistema)\033[1;33m
[9] Block \033[2;36m(Bloquear un determinado IP)\033[1;33m
[10] Desblock \033[2;36m(Desbloquear un determinado IP)\033[1;33m
[11] Add-Host \033[2;36m(Adicionar un host)\033[1;33m
[12] Firewall-block \033[2;36m(Reglas iptables block torrent, icmp [RISCOS])\033[1;33m
[13] ResetFirewall \033[2;36m(Retirar todas las reglas iptables [RISCOS])\033[1;33m
[14] BackupUsers \033[2;36m(Backup de usuarios para reinstalacion futura)\033[1;33m
[15] RestUsers \033[2;36m(Restaurar usuarios desde backup)\033[1;33m
[16] Banner \033[2;36m(Banner mensaje en ssh)\033[1;33m
[17] Herramientas \033[2;36m(Herramientas [\033[1;31mEXPERIMENTAL\033[1;30m])\033[1;33m
[18] Desinstalar \033[2;32m(Remover VpsPack)\033[0m"
read -p "[1-24]: " opcao

case $opcao in
 1)  
  Usercreate
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 2)
  UserRedefine
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 3)
  detalhesuser
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 4)
  detalhesusers
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 5)
  speedtest
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 6)
  systemdetalhes
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 7)
  htop
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 8)
  Ayuda
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 9)
  block
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 10)
  desblock
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 11)
  add-host
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 12)
  firewall-block
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 13)
  resetFirewall
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 14)
  backupusers
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 15)
  restusers
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;; 
 16)
  banner
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 17)
  tools;;
 18)
  Desinstalar;;
  *)
  id > /dev/null 2> /dev/null
esac
