#!/bin/bash
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;34m
[1] CrearUsuario \033[2;36m(Criar usuarios para SSH e OpenVPN)\033[1;34m
[2] RedefinirUsuario \033[2;36m(Opções para mudanças no usuario)\033[1;34m
[3] DetalleUsuario \033[2;36m(Mostra informações de um unico usuario !!)\033[1;34m
[4] DetalleUsuarios \033[2;36m(Mostra informações de todos os usuarios !!)\033[1;34m
[5] speedtest \033[2;36m(Teste de conexão [velocidade de banda])\033[1;34m
[6] systemdetalhes \033[2;36m(Detalhes sobre o Sistema)\033[1;34m
[7] graphicsystem \033[2;36m(Detalhes sobre o VpsPack)\033[1;34m
[8] Ayuda \033[2;36m(Mostrar um grafico com informações do sistema)\033[1;34m
[9] block \033[2;36m(Bloquear um determinado IP)\033[1;34m
[10] desblock \033[2;36m(Desbloquear um determinado IP)\033[1;34m
[11] add-host \033[2;36m(Adicionar um host)\033[1;34m
[12] firewall-block \033[2;36m(Regras iptables block torrent, icmp [RISCOS])\033[1;34m
[13] ResetFirewall \033[2;36m(Retira todas as regras iptables [RISCOS])\033[1;34m
[14] backupusers \033[2;36m(Backup dos usuarios para reinstalação futura)\033[1;34m
[15] restusers \033[2;36m(Restaurar usuarios feito backup)\033[1;34m
[16] banner \033[2;36m(Banner mensagem no ssh)\033[1;34m
[17] Atualizar \033[2;36m(Atualizar VpsPack e Configurações)\033[0m"
read -p "[1-24]: " opcao

case $opcao in
 1)  
  Usercreate
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 2)
  UserRedefine
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
  3)
  detalhesuser
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 4)
  detalhesusers
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
  5)
  speedtest
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 6)
  nbwmon
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 7)
  systemdetalhes
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 8)
  htop
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 9)
  Ayuda
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 10)
  block
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 11)
  desblock
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 12)
  add-host
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 13)
  firewall-block
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 12)
  resetFirewall
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 13)
  backupusers
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;;
 14)
  restusers
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;; 
 15)
  banner
  read -n1 -r -p " Pressione uma tecla para Abrir novamente o VpsPack..."
  VpsPack;; 
  *)
  id > /dev/null 2> /dev/null
esac
