#!/bin/bash

if [ $(id -u) -eq 0 ]
then
echo -e "\033[44;1;37m        Crear Usuário          \033[0m"
	echo -e "\033[1;32mNombre del nuevo usuario:\033[0;37m"; read -p " " name
	echo -e "\033[1;32mContraseña para el usuario $name:\033[0;37m"; read -p " " pass
	echo -e "\033[1;32mCuantos dias usuario $name debe durar:\033[0;37m"; read -p " " daysrnf
        echo -e "\033[1;32mLimite de Conexiones en SSH para $name: \033[0;37m"; read -p " " num
	echo -e "\033[0m"

if (echo $name | egrep '[^a-zA-Z0-9]' &> /dev/null)
then
echo -e "\033[1;31mError!! \033[0;31mUsted digito un nombre de usuário inválido! \033[0m"
exit
else
echo "" 1> /dev/null
fi

if (echo $pass | egrep '[^a-zA-Z0-9]' &> /dev/null)
then
echo -e "\033[1;31mError!!\033[0;31m Usted digito una pass inválida! \033[0m"
exit
else
echo "" 1> /dev/null
fi


sizemax=$(echo ${#name})
if [[ $sizemax -gt 12 ]]
then
echo -e "\033[1;31mError!! \033[0;31mUsted digito un nombre de usuário muy grande,
 Use un máximo 12 caracteres!\033[0m"
exit
else
echo "" 1> /dev/null
fi
sizemaxpass=$(echo ${#pass})
if [[ $sizemaxpass -gt 9 ]]
then
echo "\033[1;31mError!! \033[0;31mUsted digito una pass muy grande,
 Use máximo 9 caracteres!\033[0m"
exit
else
echo "" 1> /dev/null
fi
sizemaxnum=$(echo ${#num})
if [[ $sizemaxnum -gt 2 ]]
then
echo -e "\033[1;31mError!! \033[0;31mUsted digito Limite de Conexoes muy alto,
 Esta permitido un maximo de 99 conexiones!\033[0m"
exit
else
echo "" 1> /dev/null
fi
if (echo $num | egrep '[^0-9]' &> /dev/null)
then
echo -e "\033[1;31mError!! \033[0;31mUsted digito un número de conexiones inválido!\033[0m"
exit
else
echo "" 1> /dev/null
fi
if (echo $daysrnf | egrep '[^0-9]' &> /dev/null)
then
echo -e "\033[1;31mErro!! \033[0;31mUsted digito una fecha inválida!\033[0m"
exit
else
echo "" 1> /dev/null
fi
       if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name ja existe\033[0m"
	else
		valid=$(date '+%C%y/%m/%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
		(echo $pass; echo $pass)|passwd $name 2>/dev/null
                limit $name $num
ADM=$(who -m --ips)
clear
                echo -e "\033[1;32m################################\033[0m"
                echo -e "\033[1;36m                        \033[0m"
                echo -e "\033[1;36m                        \033[2;40m"
                echo -e "\033[1;36mUsuario: \033[2;37m$name"
		echo -e "\033[1;36mContraseña: \033[2;37m$pass"
		echo -e "\033[1;36mExpira: \033[2;37m$datexp"
                echo -e "\033[1;36mConexiones(SSH): \033[2;37m$num"
                echo -e "\033[1;36m                        \033[2;40m"
                echo -e "\033[1;36m                        \033[0m"
                echo -e "\033[1;32m################################\033[0m"
                echo -e "\033[1;36m                        \033[0m"
                echo -e "\033[1;36m                        \033[0m"
	    echo "$pass" > /etc/VpsPackdir/senha/$name
	    echo "$valid" > /etc/VpsPackdir/date/$name
            echo "$ADM" > /etc/VpsPackdir/UsuariosADM/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "Su usuario esta en grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	echo -e "Ou execute o Usercreate como sudo. \033[1;31msudo Usercreate\033[0m"
	else
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	fi
fi
