#!/bin/bash

if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Voce não é root"
        echo "Seu usuario esta no grupo sudo"
        echo -e "Para virar root execute \033[1;31msudo su\033[0m"
        pack
        exit
        else
        clear
        echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
        pack
        exit
        fi
fi

if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi

if [ -d /etc/VpsPackdir/date ]
then
echo ""
else
mkdir /etc/VpsPackdir/date
fi

if [ -d /etc/VpsPackdir/UsuariosADM ]
then
echo ""
else
mkdir /etc/VpsPackdir/UsuariosADM
fi
clear
echo -e "\033[1;37m VpsPacket © Script criado por: \033[2;36mManahkl \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;34m
[1] Crear_Usuario \033[2;36m(Crear usuarios para SSH y OpenVPN)\033[1;34m
[2] Redefinir_Usario \033[2;36m(Redefinir Datos De Un Usuario)\033[1;34m
[3] Transferir_Usuarios \033[2;36m(Copiar usuarios para otros servidores)\033[1;34m
[4] Detalle_Usuario \033[2;36m(Muestra informacion de un unico usuario !!)\033[1;34m
[5] Detalle_Usuarios \033[2;36m(Muestra informacion de todos los usuarios !!)\033[1;34m
[6] Usuarios_Inactivos \033[2;36m(Muestra informaçion de usuarios inactivos!!)\033[1;34m
[7] Speedtest \033[2;36m(Testeo de conexion [velocidade de banda])\033[1;34m
[8] Trafico \033[2;36m(Mostrar trafico de red en tiempo real)\033[1;34m
[9] System_Detalles \033[2;36m(Detalles sobre el Sistema)\033[1;34m
[10] Graphic_System \033[2;36m(Detalles sobre el VpsPack)\033[1;34m
[11] Ayuda \033[2;36m(Mostrar um grafico con informacion del sistema)\033[1;34m
[12] Mas \033[2;36m(Mostrar mas opciones)\033[0m"
read -p "[1-10]: " opcao

case $opcao in
 1)
  Crear_Usuario
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 2)
  Redefinir_Usuarios
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 3)
  Transferir_Usuarios
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 4)
  Detalle_Usuario
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 5)
  Detalle_Uusuarios
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
  6)
  Usuarios_Inactivos
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 7)
  Speedtest
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 8)
  Trafico
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 9)
  System_Detalles
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 10)
  htop
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 11)
  Ayuda
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 12)
  Mas
  read -n1 -r -p " Presione una tecla para Abrir nuevamente VpsPack..."
  VpsPack;;
 *)
  id > /dev/null 2> /dev/null
esac
