#!/bin/bash

if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Voce não é root"
        echo "Su usuario esta en grupo sudo"
        echo -e "Para virar root execute \033[1;31msudo su\033[0m"
        pack
        exit
        else
        clear
        echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
        pack
        exit
        fi
fi

if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi

if [ -d /etc/VpsPackdir/date ]
then
echo ""
else
mkdir /etc/VpsPackdir/date
fi

if [ -d /etc/VpsPackdir/UsuariosADM ]
then
echo ""
else
mkdir /etc/VpsPackdir/UsuariosADM
fi
clear
echo -e "\033[1;37m VpsPacket © Script Modified por: \033[2;32mManahkl KB \033[0m"
echo -e "\033[1;31mEscoja las opciones:    \033[1;31mPara Salir Ctrl + C\033[1;36m
[1] CrearUsuario \033[2;33m(Crear usuarios para SSH y OpenVPN)\033[1;36m
[2] RedefinirUsuario \033[2;33m(Opciones para mudanzas de usuario)\033[1;36m
[3] DetalleDeUsuario \033[2;33m(Mostrar informacion de un unico usuario !!)\033[1;36m
[4] DetallesDeUsuarios \033[2;33m(Mostrar informacion de usuarios activos !!)\033[1;36m
[5] UsuariosInactivos \033[2;33m(Mostrar informacion de usuarios inactivos!!)\033[1;36m
[6] Speedtest \033[2;33m(Tester de conexion [velocidad de banda])\033[1;36m
[7] SystemDetalls \033[2;33m(Detalles sobre el Sistema)\033[1;36m
[8] GraphicSystem \033[2;33m(Detalles sobre VpsPack)\033[1;36m
[9] Ayuda \033[2;33m(Mostrar un grafico con informacion del sistema)\033[1;36m
[10] Mas \033[2;33m(Mostrar mas opciones)\033[0m"
read -p "[1-10]: " opcao

case $opcao in
 1)
  Usercreate
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 2)
  UserRedefine
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 3)
  detalhesuser
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 4)
  detalhesusers
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 5)
  Usersinative
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 6)
  speedtest
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 7)
  systemdetalhes
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 8)
  htop
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 9)
  Ayuda
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 10)
  Mas
  read -n1 -r -p " Presione una tecla para abrir nuevamente VpsPack..."
  VpsPack;;
 *)
  id > /dev/null 2> /dev/null
esac
